### ISSUE TITLE
The link is invailed

### ISSUE THREAD

**Issue by yutaozuo** [TheShadow29/VC-with-GAN#1]
when I want to reproduce your experiment, it occurs the problem that "https://github.com/mozilla/DeepSpeech/releases/download/v0.1.0/deepspeech-0.1.0-models.tar.gz" is invalid.
So could you please upload the file in link?
I'm sorry to bother you, please reply me at your convenience.

**Comment by TheShadow29** [comment]
Are you sure? The link seems to be working for me. Are you trying to use wget? In that case you might need to put the link in quotes.

Also, I believe most of our experiments can be run even without deep speech model.

**Comment by yutaozuo** [comment]
Thank you for your answer.
I can download this file now, and the vc-vawgan can be run. I think that unstable network may cause this problem.
Howerver, I have another question. I want to run Sentence Embeddings.py, but i see that "ensure you have `w_prob_dict.pkl` and `w_vec_dict.pkl` in `data` directory." in Readme.
So I just want to know how can I get the `w_prob_dict.pkl` and `w_vec_dict.pkl` file?
Sorry to bother you again, please reply me at your convenience.

**Comment by TheShadow29** [comment]
@yutaozuo sorry for the delayed response. You might have to change the sentence_embedding.py (essentially comment out everything form `if __name__ == '__main__'` part) and run two functions in that file. 

For `w_prob_dict.pkl` you have two options. Either use `get_word_prob_from_corpus` this demands a corpus as an input. We used WikiText. Or you can get a csv file with unigram probabilities (we mentioned the source in the report http://norvig.com/ngrams/) and use the function `get_w_prob_from_csv`. 

For `w_vec_dict.pkl` initialize a `Sentence_Embedding` object and then call the function `prune_word_vec`. This essentially keeps only those embeddings which are present in the transcriptions since it takes a lot more time (and ram) to get the parse the whole fasttext data.

Sorry for not being completely clear in the readme.

I am also sharing the directory for all the pickle files https://drive.google.com/open?id=1FWGGEQ9wTUewBDFq5ssT4BP4cMyt8lh1

**Comment by TheShadow29** [comment]
@yutaozuo I am closing the issue if everything is solved. I have updated the readme to address the issue as well. Feel free to open a new issue if there is some other problem.

**Comment by yutaozuo** [comment]
@TheShadow29 Thanks a lot. I will run it again by following your advice.
